<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315153827 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE archived_customers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, reason_archived VARCHAR(255) NOT NULL, date_archived TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE customer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, surname VARCHAR(255) NOT NULL, phone VARCHAR(15) NOT NULL, salary DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE history_customers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, notes VARCHAR(255) NOT NULL, customer_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F41A1DC3B171EB6C ON history_customers (customer_id_id)');
        $this->addSql('CREATE TABLE loan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount DOUBLE PRECISION NOT NULL, interest_percent DOUBLE PRECISION NOT NULL, interest_amount DOUBLE PRECISION NOT NULL, total_payback DOUBLE PRECISION NOT NULL, balance_remaining DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, closing_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, extension BOOLEAN NOT NULL, loan_term_months INT NOT NULL, status VARCHAR(20) NOT NULL, interest_paid_this_month DOUBLE PRECISION DEFAULT NULL, last_rollover_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, customer_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C5D30D03B171EB6C ON loan (customer_id_id)');
        $this->addSql('CREATE TABLE payments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount_paid DOUBLE PRECISION NOT NULL, payment_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, loan_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65D29B3228FD8608 ON payments (loan_id_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE history_customers ADD CONSTRAINT FK_F41A1DC3B171EB6C FOREIGN KEY (customer_id_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE loan ADD CONSTRAINT FK_C5D30D03B171EB6C FOREIGN KEY (customer_id_id) REFERENCES customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B3228FD8608 FOREIGN KEY (loan_id_id) REFERENCES loan (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE history_customers DROP CONSTRAINT FK_F41A1DC3B171EB6C');
        $this->addSql('ALTER TABLE loan DROP CONSTRAINT FK_C5D30D03B171EB6C');
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT FK_65D29B3228FD8608');
        $this->addSql('DROP TABLE archived_customers');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE history_customers');
        $this->addSql('DROP TABLE loan');
        $this->addSql('DROP TABLE payments');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
